version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/NUTEE/auth/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall: # 배포가 끝나면 아래 명령어를 실행
    - location: scripts/deploy.sh > /dev/null 2> /dev/null < /dev/null &
      timeout: 180
      runas: ec2-user
