package kr.nutee.auth.enums;

import java.util.List;

public enum Major {
    SOCIOLOGY("SOCIOLOGY"),
    SOCIAL_SCIENCE("SOCIAL_SCIENCE"),
    ECONOMY("ECONOMY"),
    POLITICS("POLITICS"),
    BUSINESS_ADMIN("BUSINESS_ADMIN"),
    WELFARE("WELFARE"),
    IT("IT"),
    INFO_COM("INFO_COM"),
    SOFTWARE("SOFTWARE"),
    COMPUTER_SCIENCE("COMPUTER_SCIENCE"),
    GLOCAL_IT("GLOCAL_IT"),
    HUMANITIES("HUMANITIES"),
    ENGLISH("ENGLISH"),
    JAPANESE("JAPANESE"),
    CHINESE("CHINESE"),
    MISSION("MISSION"),
    MEDIA_CONTENTS("MEDIA_CONTENTS"),
    JOURNALISM("JOURNALISM"),
    DIGITAL_CONTENTS("DIGITAL_CONTENTS");

    Major(String major) {
    }

    public static List<Major> getAllMajors() {
        return List
            .of(SOCIOLOGY, SOCIAL_SCIENCE, ECONOMY, POLITICS, BUSINESS_ADMIN, WELFARE, IT, INFO_COM,
                SOFTWARE, COMPUTER_SCIENCE, GLOCAL_IT, HUMANITIES, ENGLISH, JAPANESE, CHINESE,
                MISSION, MEDIA_CONTENTS, JOURNALISM, DIGITAL_CONTENTS);
    }
}
